# Generated by Django 2.2.12 on 2021-12-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=42)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('link', models.CharField(max_length=250)),
                ('info', models.CharField(max_length=1000)),
                ('etc', models.CharField(max_length=100000)),
            ],
        ),
    ]
